# 测试配置文件

server:
  port: 端口号
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ip地址:端口号/数据库?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: 用户名
    password: 密码
    # Redis 配置
    # todo 需替换配置，然后取消注释
  redis:
    database: 1
    host: ip地址
    port: 端口号
    timeout: 5000
    password: 密码

  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
  elasticsearch:
    uris: http://ip地址:端口号
    username: 用户名
    password: 密码